"""利用規約 / Terms of Use

1. 総則 / General Provisions
1.1 本規約の目的 / Purpose of these Terms
   本規約は、本アプリケーションの利用条件を定めるものです。
   These terms set forth the conditions for using this application.

1.2 利用規約の適用範囲と変更について / Scope and Changes to Terms of Use
   本規約は本アプリケーションの全ての利用者に適用されます。開発者は必要に応じて本規約を変更することがあります。
   These terms apply to all users of this application. The developer may change these terms as necessary.

2. 利用者の定義と登録 / Definition and Registration of Users
2.1 利用者の定義 / Definition of Users
   本アプリケーションの利用者とは、本規約に同意し、本アプリケーションを使用する全ての個人または法人を指します。
   Users of this application refer to all individuals or entities who agree to these terms and use this application.

2.2 登録手続きとアカウントの管理 / Registration Procedure and Account Management
   本アプリケーションはアカウント登録を必要としません。
   This application does not require account registration.

3. サービスの内容 / Service Content
3.1 提供するサービスの説明 / Description of Provided Services
   本アプリケーションは、データ分析と予測モデルの生成を行うツールです。
   This application is a tool for data analysis and predictive model generation.

3.2 サービスの利用条件 / Service Usage Conditions
   利用者は自己責任で本アプリケーションを使用するものとします。
   Users shall use this application at their own risk.

4. 禁止事項 / Prohibited Actions
   以下の行為を禁止します：/ The following actions are prohibited:
   - 本アプリケーションの不正使用 / Misuse of this application
   - 他者への迷惑行為 / Actions that cause inconvenience to others
   - 違法行為 / Illegal activities

5. 免責事項 / Disclaimer
5.1 サービス提供者の責任範囲 / Scope of Service Provider's Responsibility
   開発者は、本アプリケーションの使用により生じた損害について一切の責任を負いません。
   The developer assumes no responsibility for any damages arising from the use of this application.

5.2 免責事項の説明 / Explanation of Disclaimer
   本アプリケーションにより生成されたデータの正確性や信頼性は保証されません。
   The accuracy and reliability of data generated by this application are not guaranteed.

6. 契約の解除 / Termination of Agreement
6.1 利用者による契約解除の方法 / Method of Agreement Termination by Users
   利用者はいつでも本アプリケーションの使用を中止することができます。
   Users can cease using this application at any time.

6.2 契約解除の条件 / Conditions for Agreement Termination by the Company
   開発者は、利用者が本規約に違反した場合、事前の通知なしにサービスの提供を中止することがあります。
   The developer may discontinue service provision without prior notice if users violate these terms.

7. 準拠法と裁判管轄 / Governing Law and Jurisdiction
7.1 準拠法 / Governing Law
   本規約の解釈にあたっては、日本法を準拠法とします。
   These terms shall be interpreted under Japanese law.

8. その他 / Miscellaneous
8.1 規約の変更 / Changes to Terms
   本規約は予告なく変更されることがあります。
   These terms may be changed without prior notice.

プライバシーポリシー / Privacy Policy

1. 個人情報の定義 / Definition of Personal Information
   個人情報とは、個人を特定できる情報を指します。
   Personal information refers to information that can identify an individual.

2. 収集する情報 / Information Collected
   本アプリケーションは、利用者から情報を収集しません。
   This application does not collect information from users.

3. 情報の利用目的 / Purpose of Information Use
   情報を収集しないため、該当しません。
   Not applicable as information is not collected.

4. 情報の共有と提供 / Sharing and Provision of Information
   情報を収集しないため、第三者との共有は行いません。
   As information is not collected, there is no sharing with third parties.

5. 情報の保護 / Information Protection
   本アプリケーションは情報を収集・保管しないため、特別なセキュリティ対策は実施していません。
   As this application does not collect or store information, no special security measures are implemented.

6. 利用者の権利 / User Rights
   情報を収集しないため、該当しません。
   Not applicable as information is not collected.

7. クッキー等の使用 / Use of Cookies
   本アプリケーションはクッキーを使用しません。
   This application does not use cookies.

8. 変更について / Changes to Policy
   本プライバシーポリシーは予告なく変更されることがあります。
   This privacy policy may be changed without prior notice.

出典 : Training_demodata_SSDSE-C-2024.csv : 独立行政法人 統計センター SSDSE-C-2024 を加工して作成
出典 : Prediction_demodata_SSDSE-C-2023.csv : 独立行政法人 統計センター SSDSE-C-2023 を加工して作成

"""
